version: '2'
services:
  gophish:
    build:
      context: ./.docker/gophish
    hostname: gophish
    container_name: gophishserver
    expose:
      - 3333
      - 80
    depends_on:
      - db
    volumes:
     # - ./gophish/mailer:/opt/gophish/mailer
     # - ./gophish/models:/opt/gophish/models
     # - ./gophish/controllers/api:/opt/gophish/controllers/api
     # - ./gophish/worker:/opt/gophish/worker
     # - ./gophish/docker:/opt/gophish/docker
      - ./gophish:/opt/gophish
    ports:
      - 3333:3333
 mail:
   image: iredmail/mariadb:stable
   hostname: mail.behavior.com
   container_name: iredmail
   domainname: test-mailclient.com
   restart: always
   env_file:
     - iredmail-docker.conf
   ports:
     - "80:80"
     - "443:443"
     - "110:110"
     - "995:995"
     - "243:143"
     - "993:993"
     - "465:465"
     - "587:587"
     - "3306:3306"
   volumes:
     - ./data/backup:/var/vmail/backup
     - ./data/mailboxes:/var/vmail/vmail1
     - ./data/mlmmj:/var/vmail/mlmmj
     - ./data/imapsieve_copy:/var/vmail/imapsieve_copy
     - ./data/custom:/opt/iredmail/custom
     - ./data/ssl:/opt/iredmail/ssl
     - ./data/mysql:/var/lib/mysql
     - ./data/clamav:/var/lib/clamav
     - ./data/sa_rules:/var/lib/spamassassin
     - ./data/postfix_queue:/var/spool/postfix
  db:
    image: mysql:5.7
    hostname: db
    container_name: rl.db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: rainloop
      MYSQL_PASSWORD: rainloop
      MYSQL_DATABASE: rainloop
    volumes:
      - mysql:/var/lib/mysql
      - tmp:/tmp
  php:
    build:
      context: ./.docker/php
    hostname: php
    container_name: rl.php
    expose:
      - 9000
    depends_on:
      - db
     - mail
    volumes:
      - ./:/var/www
      # - ./build/local/:/var/www
      - ./.docker/php/rainloop.ini:/usr/local/etc/php/conf.d/rainloop.ini
      - tmp:/tmp

  nginx:
    image: nginx:latest
    hostname: nginx
    container_name: rl.nginx
    depends_on:
      - php
    ports:
      - 543:443
      - 7000:80
    volumes:
      - ./:/var/www
      # - ./build/local/:/var/www
      - ./.docker/nginx/ssl:/etc/nginx/ssl
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - tmp:/tmp

volumes:
  mysql:
    driver: local
  maildata:
    driver: local
  mailstate:
    driver: local
  tmp:
    driver: local